Add `delete` key support
matheuswhite/scope-rs pull request #73
Opened 2024-03-31 03:49 UTC by MilhoNerfado

Adds `delete` key support on the command bar

Deletes the character on the right of the cursor when the `delete` key is pressed

2024-04-07 23:59 UTC, matheuswhite commented
There is a bug in PR. To reproduce this bug, type only one char and hit a delete. The cursor remaing in same place, but the character before the cursor is deleted.

2024-04-09 17:03 UTC, MilhoNerfado commented
> There is a bug in PR. To reproduce this bug, type only one char and hit the delete key. The cursor remaing in same place, but the character before the cursor is deleted.

I swear i did change that before submitting the PR. New commit fixing it already pushed to the branch

2024-04-25 20:25 UTC, matheuswhite requested changes

2024-04-25 20:25 UTC, matheuswhite commented on src/command_bar.rs
> +                self.update_command_list();
This line updates the command list before the change of command bar text. This bug also occurs in `Backspace` handling.

2024-05-09 19:05 UTC, MilhoNerfado commented on src/command_bar.rs
> +                self.update_command_list();
moving `self.update_command_list()` to after updating `self.command_line` fixes for both `Delete` and `Backspace`

2024-05-09 23:06 UTC, matheuswhite approved these changes

2024-05-09 23:07 UTC, merged